### PR TITLE
Experimental support for root domain. Related to #8

### PR DESCRIPTION
**Pull request by abergs**
Treat this PR as a pure experiment. I have no experience in the acme API but I thought I'd send it as an experiment to follow the guidance by the LE engineer [here](https://community.letsencrypt.org/t/confusing-on-root-domain-with-wildcard-cert/56113/3).

### CODE REVIEW

**Comment by abergs** [comment]
@sjkp Any guidance on how I could test this?

**Comment by bvdwalt** [comment]
Hi @abergs, we would also like this for our root domain. Have you had any luck testing it?

**Comment by abergs** [comment]
@bvdwalt Haven't even tried. Too little time / experience with the devflow of a "Deploy to Azure" thing and certificates to test this in an effect way.

**Comment by abergs** [comment]
@sjkp Any advice on testing this?

**Pull request closed without merging**
